# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'sebagomez'

steps:
- script: dotnet publish -o ../../Docker/root --configuration $(buildConfiguration) src/AngularWebStorageExplorer/AngularWebStorageExplorer.csproj
  displayName: 'dotnet publish'
- script: docker build -t $(dockerId)/azurestorageexplorer:$(build.buildNumber) .
  workingDirectory: $(build.SourcesDirectory)/Docker
  displayName: 'docker build'
- script: docker tag $(dockerId)/azurestorageexplorer:$(build.buildNumber) $(dockerId)/azurestorageexplorer
  displayName: 'docker tag'
- script: docker login -u $(dockerId) -p $(dockerPwd) 
  displayName: 'docker login'
- script: docker push $(dockerId)/azurestorageexplorer:$(build.buildNumber)
  displayName: 'docker push'
- script: docker push $(dockerId)/azurestorageexplorer
  displayName: 'docker push latest'
